apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inventory-api

resources:
  - ../../base

# Rewrite the placeholder image to the actual ACR-prefixed coordinate.
# Same caveat as sample-app: forks need to edit the newName to their ACR.
images:
  - name: globalretail/inventory-api
    newName: acrglobalretaildevweu389ce1.azurecr.io/globalretail/inventory-api
    newTag: main

labels:
  - includeSelectors: false
    pairs:
      environment: dev
